<template>
  <div>
    <nav-header></nav-header>
    <home-section></home-section>
    <trending-page></trending-page>
    <top-creators></top-creators>
    <categories-section></categories-section>
    <discover-section></discover-section>
  </div>
</template>
